### ISSUE TITLE
Voucher is applying twice

### ISSUE THREAD

**Issue by vaileamon** [verbb/gift-voucher#69] opened 2021-07-12 10:26 UTC
**Description**

Since the last update, when adding a gift voucher to the order, it applies to one the line items _and_ in the general order adjustments (like it was before).

update; reverted back to 2.5.9, work as usual

**Steps to reproduce**
1.
2.

**Additional info**
- Plugin version: 2.5.10
- Craft version: 3.6.17
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment] 2021-07-12 12:04
Can't say I can reproduce this. Here's a $10 voucher being redeemed on the front-end
 
![image](https://user-images.githubusercontent.com/1221575/125284343-ad5d4780-e35c-11eb-80e6-a70ad137d319.png)

and the control panel 
![image](https://user-images.githubusercontent.com/1221575/125284416-c49c3500-e35c-11eb-876a-f9e6a0b72fd5.png)

It certainly shouldn't be applying twice. The only change I believe would do this is https://github.com/verbb/gift-voucher/commit/0cb91f470aaf3e92e3b8d2b7688b69de78eef71f in order to address https://github.com/verbb/gift-voucher/issues/65

**Comment by pierrestoffe** [comment] 2021-07-19 11:53
I had the exact same issue where the discount was applied at the order level and at the line item level (each line item), but [Craft Commerce 3.4.0](https://github.com/craftcms/commerce/releases/tag/3.4.0) fixed it.

**Comment by jmauzyk** [comment] 2021-08-04 23:19
@engram-design I'm experiencing this as well. It appears to have something to do with the shipping rule `minMaxTotalType` again. When the matching shipping rule is set to _Value of products before any discounts are applied_, the voucher is applied at both the line item and order level. When set to _Value of products with applied discounts_, the voucher is only applied at the line item level.

**Comment by engram-design** [comment] 2021-08-05 01:58
@jmauzyk Can you confirm your plugin, Craft and Commerce versions?

**Comment by jmauzyk** [comment] 2021-08-05 02:39
@engram-design no problem:

Plugin: 2.5.10
Craft: Pro 3.7.7
Commerce: Pro 3.4.1

**Comment by engram-design** [comment] 2021-08-05 10:22
Alrighty, after spending most of the day understanding the new mechanism in Commerce 3.4+ that has caused this change, I've gotten to the bottom of it. However, it's a reasonable refactor of how the discount adjusters are applied, so it'll be worth testing before a release.

In short, we now apply adjusters in the following sequence:
- Shipping
- Gift Voucher (Discount)
- Discount
- Gift Voucher (Shipping)
- Tax

The biggest difference is when redeeming a voucher code, two adjusters are actually applied to an order, which is a massive pain. The `Gift Voucher (Shipping)` is the new one. This is so that the regular adjuster `Gift Voucher (Discount)` discounts the line item total, but cannot override the shipping. We apply another adjuster, but not a discount adjuster to negate the shipping cost applied to the order (if there is one, and up to the available amount on the voucher code).

As for the changed behaviour with Commerce when a discount is applied, it now spreads the amount over all line items. This is in contrast to how Gift Voucher used to work, where it was off the entire total. However, this was flawed in that it didn't really factor in shipping costs properly. Some users who had Tax rules setup for shipping found this an issue (tax was still applied, despite there being a "discount" on it). Hopefully in the future, Commerce will allow for an easier method for an adjuster to adjust shipping from a discount adjuster.

Refer to this which I'm not sure is here to stay in Commerce, judging from the comments in code - https://github.com/craftcms/commerce/blob/1598123ff13fd0c59da5b9f52e1e9fe091d719e7/src/adjusters/Discount.php#L86-L91

There's a bit of complex logic with these two "linked" adjusters, particularly when consolidating them after checkout into a single redemption, but I've put it through its paces today.

So, if you're up to testing the updated behaviour, change your `verbb/gift-voucher` requirement in `composer.json` to:

```
"require": {
  "verbb/gift-voucher": "dev-craft-3 as 2.5.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jmauzyk** [comment] 2021-08-06 19:04
@engram-design Is it possible to set up this new logic to accommodate the `registerAdjuster` setting? In cases where the voucher reduces a line item's cost to $0, this results in no tax collected for that item. We're using vouchers as e-gift cards, so we still need to collect tax on those items.

**Comment by engram-design** [comment] 2021-08-08 12:36
Unfortunately not. My testing has shown that Commerce handles discounts differently now, which requires the use of the `OrderAdjustments::EVENT_REGISTER_DISCOUNT_ADJUSTERS` event, otherwise it won't get applied.

For instance, what we currently have is the below order for adjusters:

```
craft\\commerce\\adjusters\\Shipping
craft\\commerce\\adjusters\\Discount
verbb\\giftvoucher\\adjusters\\GiftVoucherAdjuster
verbb\\giftvoucher\\adjusters\\GiftVoucherShippingAduster
craft\\commerce\\adjusters\\Tax
```

As you'll see the voucher adjuster is added alongside the discount, and the shipping adjuster added that - all before tax. And instead we want the option to change to:

```
craft\\commerce\\adjusters\\Shipping
craft\\commerce\\adjusters\\Discount
craft\\commerce\\adjusters\\Tax
verbb\\giftvoucher\\adjusters\\GiftVoucherAdjuster
verbb\\giftvoucher\\adjusters\\GiftVoucherShippingAduster
```

Unfortunately, this can't be done. The only way to register a discount adjuster is to use `OrderAdjustments::EVENT_REGISTER_DISCOUNT_ADJUSTERS` which orders those adjusters together. This is due to this troublesome code:

https://github.com/craftcms/commerce/blob/85d1250a4fc359ffd067221102057c9d9451134c/src/adjusters/Discount.php#L145-L153
 
Which not only creates the new behaviour of splitting a discount's amount over line items, but basically wipes out all `discount` adjusters, which removes our `GiftVoucherAdjuster` added to the end of adjusters order. Otherwise, this would be extremely straightforward.

There are a few ways to _maybe_ get around this.

#### 1. Change `GiftVoucherAdjuster` to be a non-`discount` adjuster type
Form what I've discussed with the Commerce team, this shouldn't be done. But if I were to set the `ADJUSTMENT_TYPE` to anything but `discount` it would allow us to apply the adjuster properly, not reliant on the order, before tax. This would essentially give us back the old behaviour.

Despite it being discouraged, this is my preferred option as it also allows us to ditch the new `GiftVoucherShippingAduster` adjuster, as that can now be factored into the voucher redeemed amount.

 #### 2. Add another adjuster for `GiftVoucherTaxAdjuster`
This just makes things much more complicated...

#### 3. Use partial payments
A major-ish refactor, and not sure if the functionality is possible - but to use partial payments to add a transaction on the cart for the redeemed amount, and "pay" a Gift Voucher-provided gateway (a manual gateway).

#### 4. Appeal to the Commerce team to "fix" this
It's changed behaviour, but it's kinda making Gift Voucher's life hell!

Soooo - I'm leaning towards option 1. and just saying "to hell with it" that it's frowned upon to have custom adjusters. It takes away so much complexity on our end, gives us more expected and predictable results, and keeps it completely separate from Commerce's handling of discounts.

**Comment by vaileamon** [comment] 2021-08-17 09:43
Any idea on when option 1 going to be shipped ?

**Comment by jerome2710** [comment] 2021-08-17 12:45
One of our clients is now experiencing this issue on a production environment as well. Is the fix tested & proven to work? Could it be released and/or is it safe to use the develop-branch (I prefer not)?

**Comment by engram-design** [comment] 2021-08-17 13:56
I been waiting for some feedback on which route to go, but likely going to steam on ahead to get this sorted, as it's becoming a liability and pretty urgent. Expect this in the next day or so.

**Comment by engram-design** [comment] 2021-08-22 05:13
Should be all resolved in [2.6.0](https://github.com/verbb/gift-voucher/releases/tag/2.6.0)

**Comment by jerome2710** [comment] 2021-08-23 10:37
@engram-design I just updated the plugin and tested the vouchers again, but I believe this isn't completely fixed yet. Please see the screenshot below: 

![Schermafbeelding 2021-08-23 om 12 31 37](https://user-images.githubusercontent.com/4600095/130433288-2f655ebf-2aee-4315-8961-c235d579ac64.png)

I added two products for €150, the voucher amount is €100, reducing it to €50. However, after choosing the shipping method for €5.95, €55.95 total, the voucher gets reapplied to the shipping costs as well, reducing it to €50 again. Vouchers shouldn't be applied to shipping, nor did this voucher even have remaining amount available.

**Comment by engram-design** [comment] 2021-08-23 10:44
Why shouldn't vouchers be applied to shipping? It's indeed a bug that it shouldn't discount any more than the total amount of the voucher value - I'd tested that thoroughly (not enough it seems).

**Comment by engram-design** [comment] 2021-08-23 12:00
@jerome2710 

Fixed in [2.6.1](https://github.com/verbb/gift-voucher/releases/tag/2.6.1) due to the urgency, but keen to hear your thoughts on whether shipping should factor into a voucher redemption.

For example you have a $50 voucher:
Item 1: $20
Item 2: $20
Shipping: $10
Nothing to pay, voucher balance $0.

or:
Item 1: $20
Item 2: $20
Shipping: $10
$10 to pay (shipping), voucher balance $10.

If you feel like this is something you'd like configurable, please open a new issue to discuss!

**Comment by jerome2710** [comment] 2021-08-23 13:05
Thank you for the quick fix! It seems to be working properly now.

I have asked our client about the shipping costs, I can think of scenarios where they would wish your option 2. Awaiting reply, I'll open a new issue when they feel the need.

**Comment by jerome2710** [comment] 2021-08-23 14:05
@engram-design please excuse me for the spam and questions, there's one more thing I would like to point out. It's more aesthetically than functional, but it might be worth mentioning and useful for others too.

Due to the fact we are now using separate adjusters, looping through the `cart.orderAdjustments` will result in the voucher being displayed twice. Once for the products and once for the shipping:

![Schermafbeelding 2021-08-23 om 15 55 58](https://user-images.githubusercontent.com/4600095/130460035-e8635588-d673-479b-9f28-c3a21b4e7202.png)

We've chosen to let the user remove the adjustment within the row, as there might be some other kind of adjuster as well (eg. Crafts discounts). One might want to refactor this view into just the description line and the amount, while displaying the specific forms for eg. adding / removing the vouchers underneath.

**Comment by engram-design** [comment] 2021-08-23 22:56
Yeah, its not great for this situation, but there's little we can do. It **must** be two different adjusters, one classified as `shipping` and `voucher` - the `shipping` one has to be classified like this in order to negate shipping cost properly, so you don't accumulate tax on shipping. Hopefully Commerce makes this easier in the future.

I suppose you could conditionally check if the adjuster is a gift voucher one **and** shipping - and just don't show it on the shipping. Or, you could combine the two costs.

It's not great, and I wish it could go back to the way it was pre Commerce 3.3/3.4.

**Comment by jerome2710** [comment] 2021-08-24 07:37
I understand. After adding my comment I refactored our code to group the adjusters visually for the user:

First showing all other adjusters, like the shipping costs themselves or any discounts:

```twig
{% for adjustment in cart.orderAdjustments if not (adjustment.sourceSnapshot.voucherId is defined) %}
    <span>{{ adjustment.name }}</span>
    <span>{{ adjustment.amount|customCommerceCurrency(cart.currency) }}</span>
{% endfor %}
```

And the voucher adjusters afterwards:

```twig
{% for adjustment in craft.commercemodule.getGroupedVoucherAdjustments(cart) %}
	<span>
		<form method="POST">
			{{ actionInput('gift-voucher/cart/remove-code') }}
			{{ redirectInput('shop/cart') }}
			{{ csrfInput() }}

			<input type="hidden" name="voucherCode" value="{{ adjustment.codeKey }}">
			
			<button type="submit" class="btn btn--x">
				{{ svg.image('icon-close', 10, 10) }}
			</button>
		</form>
		
		{{ adjustment.name }}
		
		<small>
			{{ adjustment.codeKey }} -
			{{ adjustment.currentAmount|customCommerceCurrency(cart.currency) }} / {{ adjustment.originalAmount|customCommerceCurrency(cart.currency) }}
		</small>
	</span>
	<span>{{ adjustment.amount|customCommerceCurrency(cart.currency) }}</span>
{% endfor %}
```

```php
public function getGroupedVoucherAdjustments(Order $order): array
{
    $adjustments = [];

    /** @var OrderAdjustment $adjustment */
    foreach ($order->getOrderAdjustments() as $adjustment) {
        $snapshot = $adjustment->getSourceSnapshot();

        if (!isset($snapshot['voucherId']) || !isset($snapshot['codeKey'])) {
            continue;
        }

        if (!isset($adjustments[$snapshot['codeKey']])) {
            $adjustments[$snapshot['codeKey']] = [
                'name' => $adjustment['name'],
                'codeKey' => $snapshot['codeKey'],
                'amount' => $adjustment['amount'],
                'currentAmount' => $snapshot['currentAmount'],
                'originalAmount' => $snapshot['originalAmount'],
            ];
        } else {
            $adjustments[$snapshot['codeKey']]['amount'] += $adjustment['amount'];
        }
    }

    return $adjustments;
}
```

Hopefully this might be useful for some, we are now back at the original situation of Commerce 3.3 / 3.4, which is the most favorable for the user and in terms of conversion. Thanks again for your quick responses @engram-design.

**Comment by smockensturm** [comment] 2021-11-10 22:26
Maybe someboday can answer this clearly and succinctly.

Is it possible to apply a voucher code to **everything**? Taxes, shipping, totals, everything. The whole nut.

Our client wishes to use voucher as a Gift Card. So if my Gift Card covers my cart total, I should expect to pay nothing.

**Comment by engram-design** [comment] 2021-11-10 22:36
@smockensturm That's how it currently works. 

You'd think it'd be simple enough to do `orderTotal - voucherAmount = $0`, but it doesn't work like that. The big issue is Tax on shipping, which is the reason for the two different adjusters to 1. Deduct the value from the order total (line items) and 2. Deduct the value from shipping.

Without that second, separate adjuster, shipping tax is still applied.

This is all to do with Commerce 3.3, 3.4 changes, but it should work as expected.

**Comment by smockensturm** [comment] 2021-11-10 23:04
i’m sorry. i’m dense. what two different adjusters?

i agree. it *should*. but i’m not convinced it does. obvs not clear how.

**Comment by engram-design** [comment] 2021-11-10 23:28
Those adjusters are under the hood. When you apply a code to your cart, you actually apply two adjusters to the cart:

```
verbb\giftvoucher\adjusters\GiftVoucherAdjuster
verbb\giftvoucher\adjusters\GiftVoucherShippingAduster
```

One takes off value from the line items, the other shipping. It's largely not something you have to worry about, but just an FYI of changed behaviour.

So you're saying it's not working as expected, taking off $X amount off the order total? If so, can you show what the result is on the cart once a voucher is applied to the cart?

**Comment by smockensturm** [comment] 2021-11-10 23:38
good info thank you! i’ll check back in when back at it.

**Comment by smockensturm** [comment] 2021-11-11 13:57
Perhaps this screenshot can better explain.

Here we have:
- no shipping
- a 15% discount code applied
- a voucher / gift card with 100 bucks on it

<img width="1380" alt="Screen Shot 2021-11-11 at 8 45 02 AM" src="https://user-images.githubusercontent.com/6586518/141309310-aa380532-bc4f-43d4-8c57-0ada3bebf64b.png">

> You'd think it'd be simple enough to do orderTotal - voucherAmount = $0, but it doesn't work like that. 

Is that because of the law? or an opinion?

**Comment by engram-design** [comment] 2021-11-12 03:11
Are you able to share your Tax settings (Rates/Categories/Zones), and the `FALL15` discount settings so I can recreate that?

**Comment by smockensturm** [comment] 2021-11-12 13:48
With pleasure. Attached is a txt doc with the sql inserts.

[tax-discount-inserts.sql.txt](https://github.com/verbb/gift-voucher/files/7527950/tax-discount-inserts.sql.txt)

**Comment by smockensturm** [comment] 2021-11-12 13:52
You may want to check out this checkbox setting while you're in there. Doesn't seem to make a difference either way.

`Don’t allow voucher codes to be used if discounts are applied on the order `

**Comment by engram-design** [comment] 2021-11-13 06:11
Thanks for that info, although I might be missing your country/state logic (`commerce_taxzone_countries`, `commerce_taxzone_states`), but I've applied that to a brand-new install and can't seem to immediately replicate that.

![image](https://user-images.githubusercontent.com/1221575/141607987-4a0a1843-1fff-466a-81bc-06d8c877b74e.png)

As for the stop processing logic, you'll need to also enable `Don’t apply any subsequent discounts to an order if this discount is applied` on the discount to make that work. However, I think now that a voucher code redemption isn't a discount adjuster, that requirement should be no longer an issue, so I'll get that fixed for the next version.

**Comment by engram-design** [comment] 2021-11-13 06:22
Right, so I can replicate this as soon as state-based shipping has been applied to an order, which is the trick. I'll investigate further

![image](https://user-images.githubusercontent.com/1221575/141608512-2fa8a94e-b52b-4c1f-b55a-b3deed26ac03.png)

**Comment by engram-design** [comment] 2021-11-13 10:56
Sorry for raising this issue from the dead, but @smockensturm does raise a valid issue about taxes, and the way we currently handle it is technically okay, but it does show the tax rate still. For example, see the below

![image](https://user-images.githubusercontent.com/1221575/141615576-62e5447a-f7c1-4592-99a4-974ee4d64a0b.png)

This includes $2.47 of tax, which is indeed factored into voucher redemption, but still shows it in the order totals. This is the exact same issue as we had with shipping adjusters. https://github.com/verbb/gift-voucher/issues/78

So - back to the drawing board, and I've (once again) refactored the adjuster to take into account everything. This involves going through 3 things in the order, negating the gift voucher cost until we use it all up.

1. Discount adjuster - to discount the line item sub total, which factors any discounts already applied through coupons.
2. Shipping adjuster - to remove any shipping costs (if the voucher still has credit left on it)
3. Tax adjuster - to remove any non-included tax (if the voucher still has credit left on it)

So the process is now rather than a single "$X off your order from Gift Voucher XXXXX" you'll have multiple adjuster lines, because each is a different action. To illustrate, check the example below. 

![image](https://user-images.githubusercontent.com/1221575/141615559-e76a58d7-b246-4768-855d-0abc5c6d7e5e.png)

Here, we have 3 "discounts" that the Gift Voucher plugin does, as states above.
- A discount of $34 to get our order content free
- $10 shipping removed so it's free
- $2.47 state-based tax (not included in product price) remove so it's free

My question is - will everyone be okay with this? Does this provide too much "noise" in the adjustments area of the cart? This seems to be the correct way to remove Tax and Shipping adjusters.

I'd love to get some feedback before pushing yet another change to this. It's an absolute shame this has become so complicated.

**Comment by smockensturm** [comment] 2021-11-15 22:27
This is totally bonkers.

Can you separate Vouchers from Discounts? This is misleading. This is not a discount. It is **currency**. And makes absolutely no sense when combined with a percentage discount.

Take the discount / promotion off the line items THEN apply the voucher to the subtotal.

Again, why is this so hard? Take the voucher amount off the top. At the end. Right before payment.

**Comment by engram-design** [comment] 2021-11-15 23:12
It's certainly needlessly complicated. I suppose a gift voucher is a type of discount conceptually, but it's separate to Commerce discounts you'd manage with either a percentage or an amount. It's now (as proposed) 3 separate adjusters for Discount, Tax and Shipping.

Taking a set amount off the order was how this plugin acted initially, but it doesn't properly negate other adjusters' amounts, which in turn affects the tax accrued on those amounts.

For example, see how this looks with the below, where we're just taking a set amount off the order total.

![image](https://user-images.githubusercontent.com/1221575/141866817-f7f75e13-89a7-4a04-8973-01c601cb53cd.png)

Here, we have a correct $0 amount, but it still shows Total Shipping: $10.00, Total Tax: $2.47 which is confusing.

**Comment by smockensturm** [comment] 2021-12-06 13:47
Hey. getting back to this. ( FWIW I don't mind the noise. we can solve that in display.)

But what do you say about this? (from the client)

> Also, from that same PGF/Doc example below, it looks like once the voucher code is applied we aren't collecting tax anymore. It removed $91.60 from the voucher, not $98.24.

<img width="1023" alt="Screen Shot 2021-12-06 at 8 40 58 AM" src="https://user-images.githubusercontent.com/6586518/144856880-44d85795-0ef0-449e-9b8e-20ca80abf6bd.png">

**Comment by engram-design** [comment] 2021-12-08 04:58
Yeah so that's where this breakdown might be misleading because the voucher has taken $91.60 off the order total, then $4.37 + $2.27 off of tax (a total of $98.24).

I'm sure you're wondering why the Discount adjuster can't be $98.24 (which clearly makes sense), thats because you'll see the below:

![image](https://user-images.githubusercontent.com/1221575/145146849-797b5839-46f3-4d4e-b976-fdc0aaade8b6.png)

Where the amount `-$98.24` is correct, but still shows the `$6.64` tax. This is mostly due to how Commerce handles each individual adjuster, and the only way to remove them for each category (shipping, tax, discount) is to remove them for each category. This is the reason for all the verbose breakdown in your screenshot of 3 different things.

After some more experimenting, the only close-to-acceptable solution I've found produces this:

![image](https://user-images.githubusercontent.com/1221575/145150502-c0863191-51e2-40bc-b6d9-de66ab711f1b.png)

Here the discount is applied early (after other discounts though, and shipping), and on each line item. This factors in any already-applied discounts, and subtracts the value off the voucher. This then correctly calculates the tax value to $0, because the item has no price, therefore isn't taxed.

What does raise an immediate question is that in some cases, the tax might be considered an additional amount, which needs to be factored into the redemption of a voucher. I'm not sure if that's your case.

And finally, if there's any shipping, we directly modify the already-applied shipping adjuster, but setting the amount (partial or otherwise) on the shipping. This is opposed to having another adjuster than negates the shipping.

**Comment by engram-design** [comment] 2021-12-08 05:15
I should mention my ideal scenario should be just to take off a total amount off the order. The only reason I'm not doing that is you still have the shipping/tax totals in the order totals section.

![image](https://user-images.githubusercontent.com/1221575/145152156-a44334dd-bf50-4da0-9f42-72a1b18927ef.png)

Keen on people's feedback about this before committing to this change.

**Comment by smockensturm** [comment] 2021-12-08 11:25
> Keen on people's feedback about this before committing to this change.

Me too. Would it help if you re-opened this issue? There's been a lot of discussion since you closed it.

> This is mostly due to how Commerce handles each individual adjuster

Have you talked to anyone on the Commerce team or asked them for help?

> I'm sure you're wondering why the Discount adjuster can't be $98.24 (which clearly makes sense)
> I should mention my ideal scenario should be just to take off a total amount off the order.

Everything seems to be pointing back to this. **This is the expectation.** All these explanations are helpful (technically) but to an end user or client, it doesn't make sense and doesn't matter.

> After some more experimenting, the only close-to-acceptable solution I've found produces this:

We can _probably_ make this work with some display machinations and additional math in the cart. We'll see.

> It's certainly needlessly complicated.

I keep thinking about this comment. Somebody thinks it's needed or it wouldn't be this way. If it truly is needless, it can be made better.

I really appreciate your work on this. Thank you.

**Comment by smockensturm** [comment] 2021-12-08 11:46
Soory. One more thing,

> After some more experimenting, the only close-to-acceptable solution I've found produces this:

Is this in the `dev-craft-3` ?

**Comment by aeu** [comment] 2021-12-08 16:37
Hi - reading this thread now as we are evaluating this plugin.  The main comment I would like to add is that I agree with the comment someone posted earlier, which is that a gift card is fundamentally currency, not a discount.

**Comment by engram-design** [comment] 2021-12-08 23:02
> Me too. Would it help if you re-opened this issue? There's been a lot of discussion since you closed it.

Yep, the discussion has gone slightly off-track from the original issue.

> Have you talked to anyone on the Commerce team or asked them for help?

Sure have! But from what I've been told, I'm going against the grain a little with adjusters, but I don't believe the other alternatives (creating a transaction for the redeemed amount) is great from a UX point of view. I'm circling back to see what we can come up with, whether that requires Commerce changes, etc. It gets tricky because vouchers are something that will eventually be coming natively to Commerce, and the adjusters system might be getting a revamp in coming versions.

> Everything seems to be pointing back to this. This is the expectation. All these explanations are helpful (technically) but to an end user or client, it doesn't make sense and doesn't matter.

Of course, and I agree. This was how it used to work, but Commerce 3+ updates have changed this over the years, making things much more difficult than you'd think they should be for such a "simple" task 🙄

As for the final screenshot, that's not in `craft-3` yet, but that's probably the approach I'm leaning towards. It shows the voucher at the end of the adjustments, for the total value - which is consistent with just about every store out there, and what I would expect to see as a customer (-$X off my order, including shipping). The only minor annoyance is that Total Tax and Total Shipping still show the values before the discount.
 
@aeu Fair enough! The reason that its a discount is to show it alongside other adjusters on an order, which is consistent with the UX for every other cart/checkout experience out there.

We have experimented with adding a transaction of a certain amount to an order - now that Commerce supports partial transactions. It'll require a lot more work with being able to add/remove applied vouchers and you'll need to also output any applied voucher code in the cart/checkout summary which you get for free with adjusters, but that's not the end of the world - just a hard, breaking change. More importantly, the UX is pretty weird when applying a voucher that sets the order total to $0, the cart just magically completes itself! This is either a Commerce bug, or something else, but that alone is pretty gross. 

Adding the voucher as a partial (or full) transaction certainly treats it more like currency than a discount, but it's also major work. Might be our only option!

Looking into other options to make this work for everyone.

**Comment by smockensturm** [comment] 2021-12-08 23:39
> As for the final screenshot, that's not in craft-3 yet, but that's probably the approach I'm leaning towards.

We can make that solution work (with some template logic) not ideal, but we gotta do what we gotta do.

No pressure, but our client wants to auction off $1000 gift card on 12/13. We are obviously heavily invested in your plugin at this point. I'm gonna give them a heads up that a major can of worms has opened up and we might not be able to pull it off.

**Comment by engram-design** [comment] 2021-12-09 08:20
@smockensturm Okay, so I've spent some time chatting with the Commerce crew, and we're reverting back to the 2.5.x behaviour, and using a custom adjuster type (`voucher` instead of `discount`). This fixes the original issue in https://github.com/verbb/gift-voucher/issues/65 and the OP issue here.

Let me know what you think (in `dev-craft-3`).

**Comment by jerome2710** [comment] 2021-12-09 08:46
> and we're reverting back to the 2.5.x behaviour, and using a custom adjuster type (`voucher` instead of `discount`). This fixes the original issue in #65 and the OP issue here.

Please do make this a breaking change this time. We have written some custom code to cope with the original change and will need to revert this to make it work again.

**Comment by engram-design** [comment] 2021-12-09 08:55
@jerome2710 I wasn't planning on making this a breaking change (2.7.0) because I don't think it is, purely because it's fixing a pretty vital issue, and only a change in behaviour as opposed to an actual breaking change. It's the same reason that both issues didn't have breaking change, they've just had unexpected side effects. I wouldn't want to prevent users from updating because its a major version number when there's no changes that are breaking introduced.

I certainly wasn't expecting all these changes between minor/patch versions.

**Comment by smockensturm** [comment] 2021-12-10 14:03
> Let me know what you think (in dev-craft-3).

This is great @engram-design  Works like a charm and as expected. Our client is still reviewing but I think it's solid. Thank you very much for your diligence and patience.

**Comment by engram-design** [comment] 2021-12-10 22:41
Sounds great @smockensturm , I'll be tagging 2.7.0 this weekend.

**Comment by engram-design** [comment] 2021-12-11 21:24
Hoping we can put this one to bed, in [2.7.0](https://github.com/verbb/gift-voucher/releases/tag/2.7.0)

**Closed as completed by engram-design** 2021-12-11 21:24 UTC

**Comment by smockensturm** [comment] 2021-12-16 13:27
Hey Josh. Just circling back to say all good here. 2.7.0 is deployed to production, client is happy and you can indeed put this one to bed. Until next time. :)
